version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1  
   container_name: elasticsearch
   ports:
     - "9200:9200"
   volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
     - discovery.type=single-node
  
  kibana:
   image: docker.elastic.co/kibana/kibana:7.12.1
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
  

volumes:
  elasticsearch-data:  